import type { Metadata } from "next";
import "./globals.css";
import Header from './../components/Header'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// app/layout.js (root layout)
import { cookies } from 'next/headers';


export default async function RootLayout({ children } :{children :React.ReactNode}) {
  // Get theme from cookies on the server
  const cookieStore = await cookies();
  const theme = cookieStore.get('colortheme')?.value || 'light';

  return (
    <html lang="en" data-theme={theme}>
      <body>
        <div className="bg-base-300 min-h-screen flex flex-col">
              <Header />
              
              <main className="flex-grow">
                {children}
              </main>
        
              <footer className="footer footer-center p-4 bg-base-200 text-base-content">
                <div>
                  <p className="text-sm opacity-70">Built with Next.js and DaisyUI</p>
                </div>
              </footer>
            </div>
      </body>
    </html>
  );
}